export const UPDATE_CUSTOM_FORM = "UPDATE_CUSTOM_FORM";

export const GET_CUSTOM_FORM = "GET_CUSTOM_FORM";

export const ADD_CUSTOM_FIELD = "ADD_CUSTOM_FIELD";

export const EDIT_CUSTOM_FIELD = "EDIT_CUSTONM_FIELD";
